# DB 설정
# spring.datasource.url = jdbc:mysql://localhost:3306/ictedu_db
# spring.datasource.username = ictedu
# spring.datasource.password =  1111
# spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

# 생략 가능
# server.port = 8080

# mybatis.mapper-locations=mapper/*.xml
# mybatis.type-aliases-package=com.ict.edu2

spring:
  application:
    name: edu3

  datasource:
    url: jdbc:mysql://localhost:3306/ictedu_db
    username: ictedu
    password : 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: file:D:/upload
      # static-locations: classpath:/static/

      #파일 업로드기능에서 파일이 저장될 물리적 경로를 명시

      file:
        upload-dir:D:/upload
  security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: fc0f2a1e052696d852c1539b4d217b28
              client-secret:  ZK6DTMV2noSndLUBECQhNdVxhLAeApuC
              redirect-uri: http://localhost:8080/login/oauth2/code/kakao
              authorization-grant-type: authorization_code
              client-authentication-method: client_secret_post
              client-name: Kakao
              scope:
                - profile_nickname
                - profile_image
                - account_email
            naver:
              client-id: pkOdTrbseb_iSEoDm8uF 
              client-secret:  XHB8SsXjp8
              redirect-uri: http://localhost:8080/login/oauth2/code/naver
              authorization-grant-type: authorization_code
              client-name: Naver
              scope:
                - name
                - email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response

server: 
  port: 8080
  servlet:
    context-path: /

mybatis:  
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ict.edu3

  # 비밀키 사용 (32바이트)
  #1시간
jwt:
  secret: "1OQSugv32S1qvCNSSj5GD0EmVKeI15yl"
  expiration: 3600000
